"""Installing Composer into a DjangoLux stack that never had it.

Since DjangoLux 1.8.0 the updater hands execution to Composer, so a Composer
service is part of a DjangoLux deployment rather than only the deploying
machine. Projects generated by the 1.8.0 scaffold already ship the hardened
trio; `check --fix` installs it into the ones generated before it.
"""

import re
import unittest

import yaml

from composer.agent_installer import AgentInstallError, _transform_to_installed

PROJECT = """name: demoproj

services:
  web:
    image: ${WEB_IMAGE:-demoproj:latest}
    restart: always
    networks:
      - egress
      - internal

  celery:
    image: ${WEB_IMAGE:-demoproj:latest}
    networks:
      - internal

  dlux-updater:
    image: ${WEB_IMAGE:-demoproj:latest}
    restart: always
    networks:
      - egress
      - internal

  db:
    image: postgres:16
    networks:
      - internal

volumes:
  postgres_data:
  static:
  dlux_runtime:

networks:
  egress:
    driver: bridge
  internal:
    internal: true
"""


def _install(contents=PROJECT, slug="demoproj"):
    return _transform_to_installed(contents, slug)


def _model(contents):
    return yaml.safe_load(contents)


class InstallTests(unittest.TestCase):
    def setUp(self):
        self.output = _install()
        self.model = _model(self.output)

    def test_the_result_is_valid_compose_yaml(self):
        self.assertIn("services", self.model)

    def test_all_three_composer_services_are_installed(self):
        for name in ("docker-socket-proxy", "composer-executor", "composer-agent"):
            with self.subTest(service=name):
                self.assertIn(name, self.model["services"])

    def test_the_projects_own_services_are_untouched(self):
        for name in ("web", "celery", "dlux-updater", "db"):
            with self.subTest(service=name):
                self.assertEqual(
                    self.model["services"][name], _model(PROJECT)["services"][name])

    def test_the_executor_holds_the_docker_socket_and_the_agent_does_not(self):
        """The whole point of the hardened topology."""
        executor = self.model["services"]["composer-executor"]
        agent = self.model["services"]["composer-agent"]

        self.assertTrue(any("docker.sock" in str(v) for v in executor["volumes"]))
        self.assertFalse(any("docker.sock" in str(v) for v in agent["volumes"]))

    def test_both_loops_can_see_the_runtime_volume(self):
        """Without this they cannot read update requests or publish availability."""
        for name in ("composer-executor", "composer-agent"):
            with self.subTest(service=name):
                self.assertTrue(any(
                    "dlux-runtime" in str(v) for v in self.model["services"][name]["volumes"]))

    def test_the_new_named_volumes_are_declared(self):
        self.assertIn("composer_agent_state", self.model["volumes"])
        self.assertIn("composer_exec_sock", self.model["volumes"])

    def test_the_existing_volumes_are_preserved(self):
        for name in ("postgres_data", "static", "dlux_runtime"):
            with self.subTest(volume=name):
                self.assertIn(name, self.model["volumes"])

    def test_the_agent_keeps_egress_and_reaches_the_proxy(self):
        self.assertEqual(
            self.model["services"]["composer-agent"]["networks"], ["egress", "docker_proxy"])

    def test_the_proxy_network_is_declared_and_isolated(self):
        """The project has egress, so the control path must not have internet."""
        self.assertTrue(self.model["networks"]["docker_proxy"]["internal"])

    def test_the_web_image_is_carried_into_the_composer_services(self):
        self.assertIn(
            "demoproj:latest",
            str(self.model["services"]["composer-agent"]["environment"]["WEB_IMAGE"]),
        )

    def test_installing_twice_changes_nothing(self):
        self.assertEqual(_install(self.output), self.output)


class NoEgressNetworkTests(unittest.TestCase):
    """A project without an `egress` network must not lose the control plane."""

    SOURCE = PROJECT.replace("""  egress:
    driver: bridge
""", "").replace("      - egress\n", "")

    def test_the_proxy_network_is_not_internal_when_it_is_the_agents_only_one(self):
        model = _model(_install(self.SOURCE))

        self.assertEqual(model["services"]["composer-agent"]["networks"], ["docker_proxy"])
        self.assertNotIn("internal", model["networks"]["docker_proxy"] or {})


class RefusalTests(unittest.TestCase):
    """Every refusal leaves the file untouched; none of them guess."""

    def test_an_existing_agent_makes_it_a_no_op(self):
        source = PROJECT.replace("  db:\n", "  composer-agent:\n    image: x\n\n  db:\n")
        self.assertEqual(_transform_to_installed(source, "demoproj"), source)

    def test_a_legacy_updater_makes_it_a_no_op(self):
        source = PROJECT.replace("  db:\n", "  composer-updater:\n    image: x\n\n  db:\n")
        self.assertEqual(_transform_to_installed(source, "demoproj"), source)

    def test_a_project_without_the_runtime_volume_is_refused(self):
        """Not a generated DjangoLux project; there is nothing to update inline."""
        with self.assertRaises(AgentInstallError):
            _install(PROJECT.replace("  dlux_runtime:\n", ""))

    def test_a_project_without_a_web_service_is_refused(self):
        source = re.sub(r"(?ms)^  web:\n.*?\n\n", "", PROJECT, count=1)
        with self.assertRaises(AgentInstallError):
            _install(source)

    def test_a_web_service_without_an_image_is_refused(self):
        with self.assertRaises(AgentInstallError):
            _install(PROJECT.replace("    image: ${WEB_IMAGE:-demoproj:latest}\n", "", 1))

    def test_an_orphan_socket_proxy_is_refused_rather_than_adopted(self):
        source = PROJECT.replace(
            "  db:\n", "  docker-socket-proxy:\n    image: x\n\n  db:\n")
        with self.assertRaises(AgentInstallError):
            _install(source)


if __name__ == "__main__":
    unittest.main()
